apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
  namespace: baya-tenant-baya-boulaares72
spec:
  containers:
  - name: test
    image: busybox
    command: ['sh', '-c', 'mount -t nfs 10.9.21.2:/storage /mnt && echo MOUNT_OK && ls /mnt && sleep 30']
    securityContext:
      privileged: true
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
  restartPolicy: Never
