apiVersion: v1
kind: Pod
metadata:
  name: nfs-cleaner
  namespace: tenant-baya
spec:
  restartPolicy: Never
  containers:
  - name: cleaner
    image: alpine
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: nfs
      mountPath: /storage
  volumes:
  - name: nfs
    nfs:
      server: 10.9.21.2
      path: /storage
