apiVersion: v1
kind: Secret
metadata:
  name: registry-sa-mon-registry-token
  namespace: baya-tenant-d6c84b74
  annotations:
    kubernetes.io/service-account.name: registry-sa-mon-registry
type: kubernetes.io/service-account-token
