apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-2404-golden-csi
  namespace: openshift-virtualization-os-images
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-csi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-golden-to-csi
  namespace: openshift-virtualization-os-images
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: copy
          image: busybox
          command:
            - sh
            - -c
            - |
              dd if=/source/disk.img of=/dest/disk.img bs=4M status=progress && echo DONE
          volumeMounts:
            - name: source
              mountPath: /source
            - name: dest
              mountPath: /dest
      volumes:
        - name: source
          persistentVolumeClaim:
            claimName: ubuntu-2404-golden
        - name: dest
          persistentVolumeClaim:
            claimName: ubuntu-2404-golden-csi
