apiVersion: v1
kind: Service
metadata:
  name: postgresql-nfs 
  namespace: tenant-baya
spec:
  selector: #Sélecteur permettant de trouver les Pods qui recevront le trafic.
    app: postgres-nfs #Le Service recherche tous les Pods ayant le label :
  ports:
  - port: 5432 #Port exposé par le Service.
    targetPort: 5432 #Port du conteneur PostgreSQL vers lequel le trafic sera redirigé